name: animospede
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4  
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  passwordfield: ^0.2.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.14.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts: 
        - asset: fonts/PoppinsRegular.ttf
          weight: 400
        - asset: fonts/PoppinsMedium.ttf
          weight: 500
        - asset: fonts/PoppinsLight.ttf
          weight: 300
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
